# ============ 本地开发环境 ============
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/zonghexiaoqiguanlixitong?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123456
    resources:
        static-locations: classpath:static/,file:static/

app:
    upload-dir: ./uploads

# 开发环境打印 SQL
logging:
    level:
        com.dao: debug
