# Dev profile — local development with IDE
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    servlet:
        context-path: /zonghexiaoqiguanlixitong

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/zonghexiaoqiguanlixitong?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123456
    resources:
      static-locations: classpath:static/,file:static/

file:
  upload:
    path: ./static/upload/
